blank_issues_enabled: false
contact_links:
  - name: Request user membership to Openshift or BC Gov/BCDevOps orgs, and access to create a public GitHub repo
    url: https://just-ask.developer.gov.bc.ca
    about: These tasks are now self-serve using the "Jus Ask" tool :) 
  - name: OCP4 Project Set Requests, Annotation Updates, and Quota Changes.
    url: https://registry.developer.gov.bc.ca
    about: All of these tasks are now performed in the Project Registry - make sure to update your bookmarks!
  - name: Request access to RocketChat
    url: https://developer.gov.bc.ca/docs/default/component/bc-developer-guide/rocketchat/steps-to-join-rocketchat/
    about: Did you know that most employees and contractors don't need to an invite to join Rocketchat? You can log straight in! More info at the link!
  - name: Request for an Pathfinder SSO Client in a standard realm
    url: https://bcgov.github.io/sso-requests/
    about: To create a set of Pathfinder SSO clients (in KeyCloak DEV, TEST, PROD).
  - name: Get support
    url: https://digital.gov.bc.ca/cloud/services/private/support/
    about: View different support resources and channels.

